title: Alberto Martinez Linera
logo: /foto.png
description: Ingeniero Industrial
[Descargar CV](https://upcomillas-my.sharepoint.com/personal/201802535_alu_comillas_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F201802535%5Falu%5Fcomillas%5Fedu%2FDocuments%2FICAI%2F2%20New%20trends%20in%20information%20technology%2FCV%2FAlberto%20Mart%C3%ADnez%20Li%C3%B1era%2Epdf&parent=%2Fpersonal%2F201802535%5Falu%5Fcomillas%5Fedu%2FDocuments%2FICAI%2F2%20New%20trends%20in%20information%20technology%2FCV)
#show_downloads: true
theme: jekyll-theme-minimal
